[package]
name = "spud"
version = "0.1.0"
edition = "2021"
authors = ["Ethan Kavanagh <ekavnagh@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.21.0"